apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcsim-deployment
  labels:
    app: vcsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcsim
  template:
    metadata:
      labels:
        app: vcsim
    spec:
      containers:
      - name: vcsim
        image: localhost:5000/vcsim:v0.1.0
        ports:
        - containerPort: 443
        env:
        - name: GOVC_URL
          value: "https://user:pass@0.0.0.0:443"
