apiVersion: v1
kind: Service
metadata:
  name: vcsim-service
spec:
  type: NodePort
  selector:
    app: vcsim
  ports:
    - protocol: TCP
      port: 30443
      targetPort: 443
      nodePort: 30443
