apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-terraform-vsphere
  annotations:
    company: Crossplane
    maintainer: Crossplane Maintainers <info@crossplane.io>
    source: github.com/crossplane-contrib/provider-terrafrom-vsphere
    license: Apache-2.0
spec:
  controller:
    image: crossplane/provider-terraform-vsphere-controller:VERSION
